export const provinces = [
    {id: 1, value: "Araba/Álava", postalCode: "01"},
    {id: 2, value: "Albacete", postalCode: "02"},
    {id: 3, value: "Alacant/Alicante", postalCode: "03"},
    {id: 4, value: "Almería", postalCode: "04"},
    {id: 5, value: "Ávila", postalCode: "05"},
    {id: 6, value: "Badajoz", postalCode: "06"},
    {id: 7, value: "Balears, Illes/Baleares, Islas", postalCode: "07"},
    {id: 8, value: "Barcelona", postalCode: "08"},
    {id: 9, value: "Burgos", postalCode: "09"},
    {id: 10, value: "Cáceres", postalCode: "10"},
    {id: 11, value: "Cádiz", postalCode: "11"},
    {id: 12, value: "Castelló/Castellón", postalCode: "12"},
    {id: 13, value: "Ciudad Real", postalCode: "13"},
    {id: 14, value: "Córdoba", postalCode: "14"},
    {id: 15, value: "Coruña, A", postalCode: "15"},
    {id: 16, value: "Cuenca", postalCode: "16"},
    {id: 17, value: "Girona/Gerona", postalCode: "17"},
    {id: 18, value: "Granada", postalCode: "18"},
    {id: 19, value: "Guadalajara", postalCode: "19"},
    {id: 20, value: "Gipuzkoa", postalCode: "20"},
    {id: 21, value: "Huelva", postalCode: "21"},
    {id: 22, value: "Huesca", postalCode: "22"},
    {id: 23, value: "Jaén", postalCode: "23"},
    {id: 24, value: "León", postalCode: "24"},
    {id: 25, value: "Lleida/Lérida", postalCode: "25"},
    {id: 26, value: "Rioja, La", postalCode: "26"},
    {id: 27, value: "Lugo", postalCode: "27"},
    {id: 28, value: "Madrid", postalCode: "28"},
    {id: 29, value: "Málaga", postalCode: "29"},
    {id: 30, value: "Murcia", postalCode: "30"},
    {id: 31, value: "Navarra", postalCode: "31"},
    {id: 32, value: "Ourense/Orense", postalCode: "32"},
    {id: 33, value: "Asturias", postalCode: "33"},
    {id: 34, value: "Palencia", postalCode: "34"},
    {id: 35, value: "Palmas, Las", postalCode: "35"},
    {id: 36, value: "Pontevedra", postalCode: "36"},
    {id: 37, value: "Salamanca", postalCode: "37"},
    {id: 38, value: "Santa Cruz de Tenerife", postalCode: "38"},
    {id: 39, value: "Cantabria", postalCode: "39"},
    {id: 40, value: "Segovia", postalCode: "40"},
    {id: 41, value: "Sevilla", postalCode: "41"},
    {id: 42, value: "Soria", postalCode: "42"},
    {id: 43, value: "Tarragona", postalCode: "43"},
    {id: 44, value: "Teruel", postalCode: "44"},
    {id: 45, value: "Toledo", postalCode: "45"},
    {id: 46, value: "València/Valencia", postalCode: "46"},
    {id: 47, value: "Valladolid", postalCode: "47"},
    {id: 48, value: "Bizkaia/Vizcaya", postalCode: "48"},
    {id: 49, value: "Zamora", postalCode: "49"},
    {id: 50, value: "Zaragoza", postalCode: "50"},
    {id: 51, value: "Ceuta", postalCode: "51"},
    {id: 52, value: "Melilla", postalCode: "52"}
]
